name: SVN-Notify-Config
version: 0.06
abstract: Config-driven Subversion notification
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  SVN::Notify: 2.22
  YAML: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
