abstract: Config-driven Subversion notification
author: Autrijus Tang <autrijus@autrijus.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: SVN-Notify-Config
no_index: 
  directory: 
    - inc
    - t
requires: 
  SVN::Notify: 2.62
  YAML: 0
version: 0.07
